# Generated by Django 5.0.4 on 2024-06-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddobagi_api', '0003_rename_user_pronounciation_feedback_user_pronounciation_graph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='correct_pronounciation_graph',
            field=models.ImageField(upload_to='graphs/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_pronounciation_graph',
            field=models.ImageField(upload_to='graphs/'),
        ),
    ]
